Repository cloud-native-toolkit/image-cli-tools-aws, pull requests merged in 2022-08, with the labels that each got.

#7 Updates base image to v1.4.0
  .github/workflows/docker-build.yaml
  Containerfile
  Containerfile-alpine
  Containerfile-fedora
  Dockerfile
Labels: feature, minor

#8 Updates base to v1.4.1
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#9 Updates base image to v1.4.2
  .github/workflows/docker-build.yaml
  .github/workflows/update-base-image.yaml
  Containerfile-alpine
  Containerfile-fedora
Labels: chore, patch

#10 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.3
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#11 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.4
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#12 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.5
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#13 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.6
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch
